version: 2
updates:
  # Terraform provider updates
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "mtnvencenzo"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "mtnvencenzo"
    commit-message:
      prefix: "chore"
      include: "scope"